spring.application.name=medecin
server.port=${PORT:9000}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# OpenAI (Azure)
openai.api.endpoint=${OPENAI_API_ENDPOINT:https://archimatchaiagent.openai.azure.com}
openai.api.deployment=${OPENAI_API_DEPLOYMENT:khoja-chat}
openai.api.key=${OPENAI_API_KEY:}















